HW1: Working environment setup
Danila-Pechenev/formal-lang-course pull request #1
Opened 2023-09-12 10:24 UTC by Danila-Pechenev

Proposed changes:
* Add graph utils
* Add tests for graph utils
* Add workflow for testing

2023-09-12 14:20 UTC, EgorOrachyov requested changes

2023-09-12 14:20 UTC, EgorOrachyov commented on project/graph_utils.py
> +
Далее идет пачка статик методов. Думаю, лучше сделать просто функции вне классов. Модули в python сами по себе уже как классы, так что тут как в java такое можно не делать с кучей классов

2023-09-12 14:20 UTC, EgorOrachyov commented on project/graph_utils.py
> +        # pylint: disable=E1101
А это точно надо тут?

2023-09-12 14:20 UTC, EgorOrachyov commented on tests/test_graph_utils.py
> +    assert os.path.exists("tests/test_files/output_raw.dot")
Файл существует, но будто хочется еще знать что и контент файла верный

2023-09-12 22:49 UTC, Danila-Pechenev commented on project/graph_utils.py
> +        # pylint: disable=E1101
Да, без этого линтер говорит, что Instance of 'Dot' has no 'write_raw' member, что неправда

2023-09-12 22:56 UTC, Danila-Pechenev commented on project/graph_utils.py
> +
Done

2023-09-12 22:56 UTC, Danila-Pechenev commented on tests/test_graph_utils.py
> +    assert os.path.exists("tests/test_files/output_raw.dot")
Done

2023-09-13 08:27 UTC, EgorOrachyov approved these changes

2023-09-13 08:29 UTC, merged