Task 3 | Reachability problem
Danila-Pechenev/formal-lang-course pull request #3
Opened 2023-09-24 10:36 UTC by Danila-Pechenev

Proposed changes:
* Add utils needed to solve the reachability problem
* Add tests for new functions

2023-09-25 15:55 UTC, EgorOrachyov requested changes

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +
Начиная с этого места это уже не похоже на utils, и просится в отдельный модуль

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +    )
Матрицы фактически и не используются у вас, вы просто берете из них данные, при этом совершая конвертацию. Далее идет цикл в цикле где руками по сути тензорное произведение считается. Возможно, лишнюю конвертацию стоит убрать

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +    for start1, end1, _ in zip(
зачем использовать _ если можно в zip третий список не класть просто

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +        for start2, end2, _ in zip(
зачем использовать _ если можно в zip третий список не класть просто

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +    ]
зачем делать списки, если далее все равно просто по ним проходите и добавляете стейты в автомат

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +def automaton_transitive_closure(automaton: FiniteAutomaton) -> nx.Graph:
транзитивное замыкание принимает автомат а возвращает у вас граф. Может тогда принимать граф - возвращать граф, или принимать автомат - возвращать автомат?

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +def reachability_problem(
плохое название, которое не отражает ничего по сути. Reachability - проблема просто достижимости в графе (возможно с ограничениями какими то). RPQ - запросы на достижимость в графе с решулярными ограничениями.  А вот у вас тут конкретно rpq через пересечение конечных автоматов как возможная реализация. Поэтому напрашивается папочка rpq, и в ней модуль отражающий реализацию алгоритма.

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +    final_nodes: set = set(),
Еще хорошо подумайте про интрефейс, тк далее подобных реализаций RPQ может быть много, и всем им желательно один потом интерфейс иметь для унифицированности

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +        for i, j, _ in zip(
Опять _

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +        if str(graph_states[i]).endswith("_starting")
Это какая то дичь, точно ли надо используя строки такое чекать?

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +            ) & collect_labels_set(graph2, start_state2, end_state2):
похожу тут пресечение множеств идет, как то это ультро дико. Семен Вячеславович про булеву декомпозицию матриц на паре говорил что-нибудь? 0_o

2023-09-25 15:55 UTC, EgorOrachyov commented on project/automaton_utils.py
> +            ) & collect_labels_set(graph2, start_state2, end_state2):
Подсказка в том что sci-py умеет относительно +- быстро по меркам питона тензорное произведение и пересечение матриц считать. Главное правильные матрицы получить

2023-09-25 16:58 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +def reachability_problem(
Согласен, слишком общо и неточно. Уточнил. Соответствующие папку и модуль сделал

2023-09-25 17:03 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +    for start1, end1, _ in zip(
Та просто загуглил, а как лучше по разреженной матрице итерироваться. Вот там и было так. Только мне третье значение не нужно оказалось. Стоило повнимательнее отнестись, а не тупо копировать) Поправил!

2023-09-25 17:03 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +        for start2, end2, _ in zip(
Поправил

2023-09-25 17:03 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +        for i, j, _ in zip(
Поправил

2023-09-25 17:12 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +    )
`tocoo()` здесь нужен был не просто так. Это дает возможность итерироваться по разреженной матрице через `for i,j,v in zip(matrix.row, matrix.col, matrix.data)`. Иначе приходится по-другому изворачиваться. В любом случае, если убрать эту конвертацию, появляются другие накладные расходы. Подробнее о вариантах итерации в первом ответе здесь: https://stackoverflow.com/questions/4319014/iterating-through-a-scipy-sparse-vector-or-matrix

2023-09-25 17:15 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +    ]
Незачем :) Переписал.

2023-09-25 17:21 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +def automaton_transitive_closure(automaton: FiniteAutomaton) -> nx.Graph:
В таком случае вообще нет смысла отдельную функцию городить. Убрал ее. Теперь использую напрямую из библиотеки.

2023-09-25 17:27 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +    final_nodes: set = set(),
Не уверен, что прям один и тот же интерфейс у них получится иметь. Вот уже в 4ой задаче, как видно из описания, требуется помимо прочего добавить возможность указать вариант решаемой задачи. Здесь этого не требуется. В остальном же эти 4 аргумента такими и будут. В этом смысле унифицированность сохраняется. Дальше по ходу если что-то начнет резать глаз, поменяю, сейчас же этого не требуется

2023-09-25 17:33 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +        if str(graph_states[i]).endswith("_starting")
мда.. Тут я явно был не в себе. Поменял на гораздо более адекватный и надежный вариант))

2023-09-25 17:42 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +            ) & collect_labels_set(graph2, start_state2, end_state2):
Про булеву декомпозицию -- говорил. Но с одной стороны, не уверен, что это было связано с тензорным произведением, с другой -- далеко не всё на лекции бывает понятно и запоминается. Но я хорошо помню объяснение, как здесь использовать пересечение множеств. В своей реализации я это и использовал. Помимо этого читал конспект по курсу, там тоже никаких комментариев насчет этого не было, поэтому использовал пересечение. Булева декомпозиция появляется в разделе про достижимость с несколькими источниками -- это следующая задача

2023-09-25 17:44 UTC, Danila-Pechenev commented on project/automaton_utils.py
> +            ) & collect_labels_set(graph2, start_state2, end_state2):
Да и к тому же, я не преследую цель оптимальности этой реализации. Ясно, что есть библиотечные реализации как тензорного произведения, так и пересечения автоматов в целом. Там всё круто. Я же реализовал это "руками" по приведенному в конспекте алгоритму и исходя из того, что обсуждалось на парах, чтобы сама суть алгоритма отложилась в памяти и была максимально понятна

2023-09-26 07:15 UTC, EgorOrachyov commented on project/automaton_utils.py
> +            ) & collect_labels_set(graph2, start_state2, end_state2):
Да, все верно. Пайтон в целом не тот язык чтобы прямо оптимально все решать. 

- Но, данное решение слишком наивное, и будет ощутимо медленным и прожорливым даже на небольших графах и запросах.

- в задании четко сказано использовать scipy матрицы, тут все таки подразумевается использовать их на максимальном уровне.

2023-09-26 07:17 UTC, EgorOrachyov commented on project/automaton_utils.py
> +    )
В общем тут поинт что матрицы нужны по задумке задания не для того чтобы просто по ребрам итерироваться :)

2023-09-26 07:58 UTC, EgorOrachyov requested changes

2023-09-26 07:58 UTC, EgorOrachyov commented on project/rpq/automata_intersection_rpq.py
> +                    State((end_state1, end_state2)),
Собственно, замечание остается прежним :)

У вас тут цикл в цикле, сложность Nedges(automata) x Nedges(graph), внутри каждой итерации вы строите два множества питоновских и их пересекаете

Лучшее решение в плане более оптимального расходования времени, это перенести пересечение на `kron` операцию из scipy. Тогда вы за Nedges(automata) + Nedges(graph) построите булеву декомпозицию матриц, и далее ее пересечете используя `kron`, в таком случае нагруженное вычисление перейдет на scipy. Это обязательно надо выполнить, иначе больше чем половину баллов за это задание не получить

2023-09-26 08:03 UTC, EgorOrachyov commented on project/rpq/automata_intersection_rpq.py
> +                    State((end_state1, end_state2)),
`Оптимальное` не асимптотически, а фактически, тк те же структуры и skipy матрицы, операции, работаю на порядок быстрее, тк под капотом там чистый добрый С, еще и с мЕньшим расходом памяти.

2023-09-26 08:04 UTC, EgorOrachyov commented on project/rpq/automata_intersection_rpq.py
> +                    State((end_state1, end_state2)),
А булеву декомпозицию можно поискать например в решения прошлых лет, чтобы понять о чем речь. Естественно, без copy-paste, тк это автоматически 0 баллов.

2023-09-26 14:19 UTC, Danila-Pechenev commented on project/rpq/automata_intersection_rpq.py
> +                    State((end_state1, end_state2)),
Окей, спасибо, что объяснили подробнее, что требуется. В код решений прошлых лет смотреть не стал, сам подумал, как тут применить булеву декомпозицию, вроде понял. Всё переписал. Посмотрите, пожалуйста.

2023-09-27 12:55 UTC, EgorOrachyov approved these changes

2023-09-27 13:03 UTC, merged