Task 4 | BFS-based RPQ
Danila-Pechenev/formal-lang-course pull request #4
Opened 2023-10-03 12:52 UTC by Danila-Pechenev

Proposed changes:
* Implement functions for BFS-based RPQ
* Add corresponding tests

2023-10-03 17:36 UTC, EgorOrachyov requested changes

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/bfs_rpq.py
> +    print(type(matrix1.get_shape()[0]))
дебажный print

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/bfs_rpq.py
> +    task_type: int = 1,
Как минимум вместо task_type Enum, как максимум две разные функции.

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/bfs_rpq.py
> +    else:
Все таки две разные функции просятся

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/utils.py
> +import numpy as np
Слово utils это антипаттерн. Вы может дать модулю более осмысленное название, даже если в нем всего одна функция будет

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/bfs_rpq.py
> +    task_type: int = 1,
Тоже самое, task_type

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/bfs_rpq.py
> +    else:
тоде task_type

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/bfs_rpq.py
> +    task_type: int = 1,
Тоже task_type

2023-10-03 17:36 UTC, EgorOrachyov commented on project/rpq/bfs_rpq.py
> +    return dsum
**Самый главный вопрос и основное замечание: А зачем тут требуются ПЛОТНЫЕ матрицы?**

Насколько знаю, bfs rpq выражается с использованием разреженных матрицы. Плотными вы сразу ограничиваете себе на размер графа и автомата. Асмиптотика памяти ужасная. Если не исправить реализацию, то боюсь в эксперинтах даже небольшие графы рискуют не влезть по памяти

2023-10-03 19:14 UTC, Danila-Pechenev commented on project/rpq/bfs_rpq.py
> +    return dsum
Согласен, все замечания исправил. Посмотрите, пожалуйста

2023-10-04 10:59 UTC, EgorOrachyov approved these changes

2023-10-04 11:00 UTC, merged