Task 6 | CFG utils
Danila-Pechenev/formal-lang-course pull request #5
Opened 2023-10-15 14:28 UTC by Danila-Pechenev

Since task5 and task5_bonus are not in the actual condition yet, I've decided to perform task 6 first. Implemented CFG utils according to the task and added corresponding tests.

2023-10-19 08:12 UTC, EgorOrachyov requested changes

2023-10-19 08:12 UTC, EgorOrachyov commented on project/cfg_utils.py
> +def _check_path(path: str) -> None:
А это точно в этом модуле должно быть?

2023-10-19 08:12 UTC, EgorOrachyov commented on project/cfg_utils.py
> +import os
`ЧТО-ТО_utils` не очень хорожее название. Не бойтесь дать более осмысленное название, или без слова utils вовсе, оно смысла не несет

2023-10-19 13:35 UTC, Danila-Pechenev commented on project/cfg_utils.py
> +import os
Все поправил

2023-10-25 08:45 UTC, EgorOrachyov approved these changes

2023-10-25 08:45 UTC, EgorOrachyov commented on project/cfg_operations.py
> -import os
Можно просто cfg.py , в принципе другого cfg не предполагается

2023-10-25 09:08 UTC, Danila-Pechenev commented on project/cfg_operations.py
> -import os
Applied

2023-10-25 09:08 UTC, merged