Task 9 | CFPQ based on matrix multiplication
Danila-Pechenev/formal-lang-course pull request #8
Opened 2023-11-12 14:09 UTC by Danila-Pechenev

Proposed changes:
- Add CFPQ based on matrix multiplication
- Add corresponding tests

2023-11-20 16:08 UTC, EgorOrachyov requested changes

2023-11-20 16:08 UTC, EgorOrachyov commented on project/cfpq/matrix_alg.py
> +            matrices[v][i, j] = True
Единственный момент который смутил, это то что матрицы сммежности руками строятся. Ранее в дз разве уже не делалось что то вроде булевой декомпозиции конечного автомата (граф это своего рода автомат) ?
Или вот например такую штуку нельза заюзать тут https://networkx.org/documentation/stable/reference/generated/networkx.linalg.graphmatrix.adjacency_matrix.html ?

2023-11-22 09:31 UTC, Danila-Pechenev commented on project/cfpq/matrix_alg.py
> +            matrices[v][i, j] = True
Думаю, не получится заюзать здесь. Ведь тут мы не просто строим adjacency_matrix, как было раньше. Мы строим N матриц, где N -- это количество нетерминалов. И в каждой такой матрице M для нетерминала Si: M[i, j] = True <=> существует продукция Si -> l и ребро (i, l, j) исходного графа. То есть здесь нам необходимо не только существование ребра, но и существование продукции, и функция adjacency_matrix это не проверяет. Можно, конечно, что-то накастылять, но так или иначе придется пройти по ребрам и посмотреть на продукции. Так что, на мой взгляд, лучше, чем то, что есть, сложно написать

2023-11-22 10:04 UTC, EgorOrachyov commented on project/cfpq/matrix_alg.py
> +            matrices[v][i, j] = True
Хорошо, звучит разумно. Хотя, если я правильно помню алгоритм, то метки на ребрах вида Li заменяются на нетерминалы виды Si -> Li (если такое правило в wcfg). Т.е. получается что булева декомпозция, просто надо сложить матрицы всех Li... если на все эти метки ссылается один нетерминал S' (S' -> L1, S' -> L2, ...). 

Вот тут в 7 строке идет Union, что по сути сложение булевых матриц 
![image](https://github.com/Danila-Pechenev/formal-lang-course/assets/31863304/8006b074-10bf-4f2a-a5ad-c7c68a176ae1)

2023-11-22 10:04 UTC, EgorOrachyov approved these changes

2023-11-24 16:09 UTC, merged