Task 10 | Tensor-based CFPQ
Danila-Pechenev/formal-lang-course pull request #9
Opened 2023-11-28 20:47 UTC by Danila-Pechenev

Тензорный алгоритм для CFPQ. Для удобства создал класс BooleanDecomposition, инкапсулировав в нем необходимую логику для работы с булевыми декомпозициями. Тесты расширены.

2023-12-01 16:14 UTC, EgorOrachyov requested changes

2023-12-01 16:14 UTC, EgorOrachyov commented on project/cfpq/tensor_alg.py
> +        for (i, j) in zip(x, y):
Вот этот момент меня смущает - вычислять используя матрицы произведение, чтобы потом получить список элементов, чтобы потом модифицировать матрицу графа (декомпозиции графа).

Если мне не изменяет память, то после пересечения и замыкания, матрицы блочная, можно вырезать блоки по нужным координатам (start final state), и просто прибавлять к матрице графа по нужному нетерминалу

2023-12-02 19:56 UTC, Danila-Pechenev commented on project/cfpq/tensor_alg.py
> +        for (i, j) in zip(x, y):
Всё так. Поправил

2023-12-03 18:37 UTC, EgorOrachyov approved these changes

2023-12-03 18:38 UTC, merged